--- 
- name: deploy with pipeline
  hosts: local
  become: true
  remote_user: ansadmin

  tasks:
      - name: remove container
        docker_container:
             name: "{{ container_name }}"
             state: absent
        ignore_errors: yes

      - name: RUN a container
        docker_container:
          name: "{{ container_name }}"
          image: "{{ image_name }}:{{ image_tag }}"
          state: started
          restart: yes
          ports:
             - "{{ port }}:8080"
        register: result
      - debug:
          msg: "{{ result }}"
    